= Events Guide for developers

== Introduction

This guide explains required actions to generate application logs in the format expected by the Monitoring Platform.
Application logs can be applied to both new and legacy applications.

=== Required Fields

Refer to <<../event-specifications.adoc#Required fields,Required Fields>> for more information.

== Logback and SLF4J

This guide targets Java based applications using of `logback` and `SLF4J` as logging framework.

=== Dependencies

Logstash-logback-encoder is an appender for Logback that allows  to encode Log messages into JSON.
JSON content is directly structured, no need to parse with regex, aggregate rows, etc.
 To use this appender, it would be necessary first of all to recover the good dependency:

```xml
<dependency>
  <groupId>net.logstash.logback</groupId>
  <artifactId>logstash-logback-encoder</artifactId>
  <version>3.4</version>
</dependency>
```

Once this dependency is recovered, the configuration of logback.xml is simple

```xml
<appender name=”STDOUT” class=”ch.qos.logback.core.ConsoleAppender”>
  <encoder class=”net.logstash.logback.encoder.LogstashEncoder”/>
</appender>
```

=== Standard Fields

These fields will appear in every LoggingEvent generated by our appender.
The field names listed here are the default field names.


|===
|Field |Description

|@timestamp
|Time of the log event. (yyyy-MM-dd'T'HH:mm:ss.SSSZZ)

|@version
|Logstash format version

|message
|Formatted log message of the event

|logger_name
|Name of the logger that logged the event

|thread_name
|Name of the thread that logged the event

|level
|String name of the level of the event

|level_value
|Integer value of the level of the event

|stack_trace
|(Only if a throwable was logged) The stacktrace of the throwable. Stackframes are separated by line endings.

|tags
|(Only if tags are found) The names of any markers not explicitly handled.
|===

=== Adding additionnal fields

There are two ways to add specific fields:

* <<Custom fields>>
* <<MDC fields>>

==== Custom fields

They allow to define fields common to all the application (see example below)
```xml
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
       <encoder class="net.logstash.logback.encoder.LogstashEncoder">
         <customFields>{"type": "logExample", "project": "my-project"}</customFields>
       </encode>
    </appender>
```
==== MDC fields

They allow to define contextual fields at runtime (see example below)
```java
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.slf4j.MDC;

public class LogbackExample {
    private static Logger logger = LoggerFactory.getLogger(LogbackExample .class);

    public static void main(String[] args) {
      //Adding stuff in the log context
      MDC.put("first", "Dorothy");
      logger.debug("Debug log message");
      logger.info("Info log message");
      //Removing stuff from the log context
      MDC.remove("first", "Dorothy");
      logger.error("Error log message");
    }
}
```
The diagnostic context is managed on a per thread basis, allowing each server thread to bear a distinct MDC stamp.
MDC operations such as put() and get() affect only the MDC of the current thread, and the children of the current thread.
The MDC in other threads remain unaffected.
Given that MDC information is managed on a per thread basis, each thread will have its own copy of the MDC.
Thus, there is no need for the developer to worry about thread-safety or synchronization when programming with the MDC because it handles these issues safely and transparently.

Refer to link:https://logback.qos.ch/manual/mdc.html[MDC] for more information.

=== Configuring logstash

Events are now properly formatted, we need to configure a dataforwarder such as <<../dataforwarder.adoc#logstash,logstash>>.
