drop table if exists metadata cascade
drop table if exists metadata cascade
drop table if exists referential cascade
drop table if exists referential_metadata_item_set cascade
create table metadata (metadata_id  bigserial not null, key varchar(255), value varchar(255), primary key (metadata_id))
create table referential (referential_id  bigserial not null, key varchar(255), timestamp varchar(255), value varchar(255), primary key (referential_id))
create table referential_metadata_item_set (referential_referential_id int8 not null, metadata_item_set_metadata_id int8 not null, primary key (referential_referential_id, metadata_item_set_metadata_id))
alter table referential_metadata_item_set add constraint UK_iqhaeklnsj9bg0gstauha98es unique (metadata_item_set_metadata_id)
alter table referential_metadata_item_set add constraint FKp7bh6u3u108wcnojymcggaw2w foreign key (metadata_item_set_metadata_id) references metadata
alter table referential_metadata_item_set add constraint FKq3j9svg66smnuyedwa0wn0tip foreign key (referential_referential_id) references referential
drop table if exists grokdata cascade
create table grokdata (grokdata_id  bigserial not null, key varchar(255), value varchar(1200), primary key (grokdata_id))
insert into grokdata (key,value) values('JAVACLASS','(?:[a-zA-Z0-9-]+\.)+[A-Za-z0-9$]+')
insert into grokdata (key,value) values('JAVAFILE','(?:[A-Za-z0-9_.-]+)')
insert into grokdata (key,value) values('JAVASTACKTRACEPART','at %{JAVACLASS:class}\.%{WORD:method}\(%{JAVAFILE:file}:%{NUMBER:line}\)')
insert into grokdata (key,value) values('NETSCREENSESSIONLOG','%{SYSLOGTIMESTAMP:date} %{IPORHOST:device} %{IPORHOST}: NetScreen device_id=%{WORD:device_id}%{DATA}: start_time=%{QUOTEDSTRING:start_time} duration=%{INT:duration} policy_id=%{INT:policy_id} service=%{DATA:service} proto=%{INT:proto} src zone=%{WORD:src_zone} dst zone=%{WORD:dst_zone} action=%{WORD:action} sent=%{INT:sent} rcvd=%{INT:rcvd} src=%{IPORHOST:src_ip} dst=%{IPORHOST:dst_ip} src_port=%{INT:src_port} dst_port=%{INT:dst_port} src-xlated ip=%{IPORHOST:src_xlated_ip} port=%{INT:src_xlated_port} dst-xlated ip=%{IPORHOST:dst_xlated_ip} port=%{INT:dst_xlated_port} session_id=%{INT:session_id} reason=%{GREEDYDATA:reason}')
insert into grokdata (key,value) values('HAPROXYTIME','(?!<[0-9])%{HOUR:haproxy_hour}:%{MINUTE:haproxy_minute}(?::%{SECOND:haproxy_second})(?![0-9])')
insert into grokdata (key,value) values('HAPROXYDATE','%{MONTHDAY:haproxy_monthday}/%{MONTH:haproxy_month}/%{YEAR:haproxy_year}:%{HAPROXYTIME:haproxy_time}.%{INT:haproxy_milliseconds}')
insert into grokdata (key,value) values('HAPROXYCAPTUREDREQUESTHEADERS','%{DATA:captured_request_headers}')
insert into grokdata (key,value) values('HAPROXYCAPTUREDRESPONSEHEADERS','%{DATA:captured_response_headers}')
insert into grokdata (key,value) values('HAPROXYHTTP','%{SYSLOGTIMESTAMP:syslog_timestamp} %{IPORHOST:syslog_server} %{SYSLOGPROG}: %{IP:client_ip}:%{INT:client_port} \[%{HAPROXYDATE:accept_date}\] %{NOTSPACE:frontend_name} %{NOTSPACE:backend_name}/%{NOTSPACE:server_name} %{INT:time_request}/%{INT:time_queue}/%{INT:time_backend_connect}/%{INT:time_backend_response}/%{NOTSPACE:time_duration} %{INT:http_status_code} %{NOTSPACE:bytes_read} %{DATA:captured_request_cookie} %{DATA:captured_response_cookie} %{NOTSPACE:termination_state} %{INT:actconn}/%{INT:feconn}/%{INT:beconn}/%{INT:srvconn}/%{NOTSPACE:retries} %{INT:srv_queue}/%{INT:backend_queue} (\{%{HAPROXYCAPTUREDREQUESTHEADERS}\})?( )?(\{%{HAPROXYCAPTUREDRESPONSEHEADERS}\})?( )?"%{WORD:http_verb} %{URIPATHPARAM:http_request}( HTTP/%{NUMBER:http_version}")?')
insert into grokdata (key,value) values('HAPROXYTCP','%{SYSLOGTIMESTAMP:syslog_timestamp} %{IPORHOST:syslog_server} %{SYSLOGPROG}: %{IP:client_ip}:%{INT:client_port} \[%{HAPROXYDATE:accept_date}\] %{NOTSPACE:frontend_name} %{NOTSPACE:backend_name}/%{NOTSPACE:server_name} %{INT:time_queue}/%{INT:time_backend_connect}/%{NOTSPACE:time_duration} %{NOTSPACE:bytes_read} %{NOTSPACE:termination_state} %{INT:actconn}/%{INT:feconn}/%{INT:beconn}/%{INT:srvconn}/%{NOTSPACE:retries} %{INT:srv_queue}/%{INT:backend_queue}')
insert into grokdata (key,value) values('SYSLOGBASE2','(?:%{SYSLOGTIMESTAMP:timestamp}|%{TIMESTAMP_ISO8601:timestamp8601}) (?:%{SYSLOGFACILITY} )?%{SYSLOGHOST:logsource} %{SYSLOGPROG}:')
insert into grokdata (key,value) values('SYSLOGPAMSESSION','%{SYSLOGBASE} (?=%{GREEDYDATA:message})%{WORD:pam_module}\(%{DATA:pam_caller}\): session %{WORD:pam_session_state} for user %{USERNAME:username}(?: by %{GREEDYDATA:pam_by})?')
insert into grokdata (key,value) values('CRON_ACTION','[A-Z ]+')
insert into grokdata (key,value) values('CRONLOG','%{SYSLOGBASE} \(%{USER:user}\) %{CRON_ACTION:action} \(%{DATA:message}\)')
insert into grokdata (key,value) values('SYSLOGLINE','%{SYSLOGBASE2} %{GREEDYDATA:message}')
insert into grokdata (key,value) values('NAGIOSTIME','\[%{NUMBER:nagios_epoch}\]')
insert into grokdata (key,value) values('NAGIOS_TYPE_CURRENT_SERVICE_STATE','CURRENT SERVICE STATE')
insert into grokdata (key,value) values('NAGIOS_TYPE_CURRENT_HOST_STATE','CURRENT HOST STATE')
insert into grokdata (key,value) values('NAGIOS_TYPE_SERVICE_NOTIFICATION','SERVICE NOTIFICATION')
insert into grokdata (key,value) values('NAGIOS_TYPE_HOST_NOTIFICATION','HOST NOTIFICATION')
insert into grokdata (key,value) values('NAGIOS_TYPE_SERVICE_ALERT','SERVICE ALERT')
insert into grokdata (key,value) values('NAGIOS_TYPE_HOST_ALERT','HOST ALERT')
insert into grokdata (key,value) values('NAGIOS_TYPE_SERVICE_FLAPPING_ALERT','SERVICE FLAPPING ALERT')
insert into grokdata (key,value) values('NAGIOS_TYPE_HOST_FLAPPING_ALERT','HOST FLAPPING ALERT')
insert into grokdata (key,value) values('NAGIOS_TYPE_SERVICE_DOWNTIME_ALERT','SERVICE DOWNTIME ALERT')
insert into grokdata (key,value) values('NAGIOS_TYPE_HOST_DOWNTIME_ALERT','HOST DOWNTIME ALERT')
insert into grokdata (key,value) values('NAGIOS_TYPE_PASSIVE_SERVICE_CHECK','PASSIVE SERVICE CHECK')
insert into grokdata (key,value) values('NAGIOS_TYPE_PASSIVE_HOST_CHECK','PASSIVE HOST CHECK')
insert into grokdata (key,value) values('NAGIOS_TYPE_SERVICE_EVENT_HANDLER','SERVICE EVENT HANDLER')
insert into grokdata (key,value) values('NAGIOS_TYPE_HOST_EVENT_HANDLER','HOST EVENT HANDLER')
insert into grokdata (key,value) values('NAGIOS_TYPE_EXTERNAL_COMMAND','EXTERNAL COMMAND')
insert into grokdata (key,value) values('NAGIOS_TYPE_TIMEPERIOD_TRANSITION','TIMEPERIOD TRANSITION')
insert into grokdata (key,value) values('NAGIOS_EC_DISABLE_SVC_CHECK','DISABLE_SVC_CHECK')
insert into grokdata (key,value) values('NAGIOS_EC_ENABLE_SVC_CHECK','ENABLE_SVC_CHECK')
insert into grokdata (key,value) values('NAGIOS_EC_DISABLE_HOST_CHECK','DISABLE_HOST_CHECK')
insert into grokdata (key,value) values('NAGIOS_EC_ENABLE_HOST_CHECK','ENABLE_HOST_CHECK')
insert into grokdata (key,value) values('NAGIOS_EC_PROCESS_SERVICE_CHECK_RESULT','PROCESS_SERVICE_CHECK_RESULT')
insert into grokdata (key,value) values('NAGIOS_EC_PROCESS_HOST_CHECK_RESULT','PROCESS_HOST_CHECK_RESULT')
insert into grokdata (key,value) values('NAGIOS_EC_SCHEDULE_SERVICE_DOWNTIME','SCHEDULE_SERVICE_DOWNTIME')
insert into grokdata (key,value) values('NAGIOS_EC_SCHEDULE_HOST_DOWNTIME','SCHEDULE_HOST_DOWNTIME')
insert into grokdata (key,value) values('NAGIOS_WARNING','Warning:%{SPACE}%{GREEDYDATA:nagios_message}')
insert into grokdata (key,value) values('NAGIOS_CURRENT_SERVICE_STATE','%{NAGIOS_TYPE_CURRENT_SERVICE_STATE:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_service};%{DATA:nagios_state};%{DATA:nagios_statetype};%{DATA:nagios_statecode};%{GREEDYDATA:nagios_message}')
insert into grokdata (key,value) values('NAGIOS_CURRENT_HOST_STATE','%{NAGIOS_TYPE_CURRENT_HOST_STATE:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_state};%{DATA:nagios_statetype};%{DATA:nagios_statecode};%{GREEDYDATA:nagios_message}')
insert into grokdata (key,value) values('NAGIOS_SERVICE_NOTIFICATION','%{NAGIOS_TYPE_SERVICE_NOTIFICATION:nagios_type}: %{DATA:nagios_notifyname};%{DATA:nagios_hostname};%{DATA:nagios_service};%{DATA:nagios_state};%{DATA:nagios_contact};%{GREEDYDATA:nagios_message}')
insert into grokdata (key,value) values('NAGIOS_HOST_NOTIFICATION','%{NAGIOS_TYPE_HOST_NOTIFICATION}: %{DATA:nagios_notifyname};%{DATA:nagios_hostname};%{DATA:nagios_state};%{DATA:nagios_contact};%{GREEDYDATA:nagios_message}')
insert into grokdata (key,value) values('NAGIOS_SERVICE_ALERT','%{NAGIOS_TYPE_SERVICE_ALERT:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_service};%{DATA:nagios_state};%{DATA:nagios_statelevel};%{NUMBER:nagios_attempt};%{GREEDYDATA:nagios_message}')
insert into grokdata (key,value) values('NAGIOS_HOST_ALERT','%{NAGIOS_TYPE_HOST_ALERT:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_state};%{DATA:nagios_statelevel};%{NUMBER:nagios_attempt};%{GREEDYDATA:nagios_message}')
insert into grokdata (key,value) values('NAGIOS_SERVICE_FLAPPING_ALERT','%{NAGIOS_TYPE_SERVICE_FLAPPING_ALERT:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_service};%{DATA:nagios_state};%{GREEDYDATA:nagios_message}')
insert into grokdata (key,value) values('NAGIOS_HOST_FLAPPING_ALERT','%{NAGIOS_TYPE_HOST_FLAPPING_ALERT:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_state};%{GREEDYDATA:nagios_message}')
insert into grokdata (key,value) values('NAGIOS_SERVICE_DOWNTIME_ALERT','%{NAGIOS_TYPE_SERVICE_DOWNTIME_ALERT:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_service};%{DATA:nagios_state};%{GREEDYDATA:nagios_comment}')
insert into grokdata (key,value) values('NAGIOS_HOST_DOWNTIME_ALERT','%{NAGIOS_TYPE_HOST_DOWNTIME_ALERT:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_state};%{GREEDYDATA:nagios_comment}')
insert into grokdata (key,value) values('NAGIOS_PASSIVE_SERVICE_CHECK','%{NAGIOS_TYPE_PASSIVE_SERVICE_CHECK:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_service};%{DATA:nagios_state};%{GREEDYDATA:nagios_comment}')
insert into grokdata (key,value) values('NAGIOS_PASSIVE_HOST_CHECK','%{NAGIOS_TYPE_PASSIVE_HOST_CHECK:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_state};%{GREEDYDATA:nagios_comment}')
insert into grokdata (key,value) values('NAGIOS_SERVICE_EVENT_HANDLER','%{NAGIOS_TYPE_SERVICE_EVENT_HANDLER:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_service};%{DATA:nagios_state};%{DATA:nagios_statelevel};%{DATA:nagios_event_handler_name}')
insert into grokdata (key,value) values('NAGIOS_HOST_EVENT_HANDLER','%{NAGIOS_TYPE_HOST_EVENT_HANDLER:nagios_type}: %{DATA:nagios_hostname};%{DATA:nagios_state};%{DATA:nagios_statelevel};%{DATA:nagios_event_handler_name}')
insert into grokdata (key,value) values('NAGIOS_TIMEPERIOD_TRANSITION','%{NAGIOS_TYPE_TIMEPERIOD_TRANSITION:nagios_type}: %{DATA:nagios_service};%{DATA:nagios_unknown1};%{DATA:nagios_unknown2};')
insert into grokdata (key,value) values('NAGIOS_EC_LINE_DISABLE_SVC_CHECK','%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_DISABLE_SVC_CHECK:nagios_command};%{DATA:nagios_hostname};%{DATA:nagios_service}')
insert into grokdata (key,value) values('NAGIOS_EC_LINE_DISABLE_HOST_CHECK','%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_DISABLE_HOST_CHECK:nagios_command};%{DATA:nagios_hostname}')
insert into grokdata (key,value) values('NAGIOS_EC_LINE_ENABLE_SVC_CHECK','%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_ENABLE_SVC_CHECK:nagios_command};%{DATA:nagios_hostname};%{DATA:nagios_service}')
insert into grokdata (key,value) values('NAGIOS_EC_LINE_ENABLE_HOST_CHECK','%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_ENABLE_HOST_CHECK:nagios_command};%{DATA:nagios_hostname}')
insert into grokdata (key,value) values('NAGIOS_EC_LINE_PROCESS_SERVICE_CHECK_RESULT','%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_PROCESS_SERVICE_CHECK_RESULT:nagios_command};%{DATA:nagios_hostname};%{DATA:nagios_service};%{DATA:nagios_state};%{GREEDYDATA:nagios_check_result}')
insert into grokdata (key,value) values('NAGIOS_EC_LINE_PROCESS_HOST_CHECK_RESULT','%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_PROCESS_HOST_CHECK_RESULT:nagios_command};%{DATA:nagios_hostname};%{DATA:nagios_state};%{GREEDYDATA:nagios_check_result}')
insert into grokdata (key,value) values('NAGIOS_EC_LINE_SCHEDULE_HOST_DOWNTIME','%{NAGIOS_TYPE_EXTERNAL_COMMAND:nagios_type}: %{NAGIOS_EC_SCHEDULE_HOST_DOWNTIME:nagios_command};%{DATA:nagios_hostname};%{NUMBER:nagios_start_time};%{NUMBER:nagios_end_time};%{NUMBER:nagios_fixed};%{NUMBER:nagios_trigger_id};%{NUMBER:nagios_duration};%{DATA:author};%{DATA:comment}')
insert into grokdata (key,value) values('NAGIOSLOGLINE','%{NAGIOSTIME} (?:%{NAGIOS_WARNING}|%{NAGIOS_CURRENT_SERVICE_STATE}|%{NAGIOS_CURRENT_HOST_STATE}|%{NAGIOS_SERVICE_NOTIFICATION}|%{NAGIOS_HOST_NOTIFICATION}|%{NAGIOS_SERVICE_ALERT}|%{NAGIOS_HOST_ALERT}|%{NAGIOS_SERVICE_FLAPPING_ALERT}|%{NAGIOS_HOST_FLAPPING_ALERT}|%{NAGIOS_SERVICE_DOWNTIME_ALERT}|%{NAGIOS_HOST_DOWNTIME_ALERT}|%{NAGIOS_PASSIVE_SERVICE_CHECK}|%{NAGIOS_PASSIVE_HOST_CHECK}|%{NAGIOS_SERVICE_EVENT_HANDLER}|%{NAGIOS_HOST_EVENT_HANDLER}|%{NAGIOS_TIMEPERIOD_TRANSITION}|%{NAGIOS_EC_LINE_DISABLE_SVC_CHECK}|%{NAGIOS_EC_LINE_ENABLE_SVC_CHECK}|%{NAGIOS_EC_LINE_DISABLE_HOST_CHECK|%{NAGIOS_EC_LINE_ENABLE_HOST_CHECK}|%{NAGIOS_EC_LINE_PROCESS_HOST_CHECK_RESULT}|%{NAGIOS_EC_LINE_PROCESS_SERVICE_CHECK_RESULT}|%{NAGIOS_EC_LINE_SCHEDULE_HOST_DOWNTIME})')
insert into grokdata (key,value) values('RUBY_LOGLEVEL','(?:DEBUG|FATAL|ERROR|WARN|INFO)')
insert into grokdata (key,value) values('RUBY_LOGGER','[DFEWI], \[%{TIMESTAMP_ISO8601:timestamp} #%{POSINT:pid}\] *%{RUBY_LOGLEVEL:loglevel} -- +%{DATA:progname}: %{GREEDYDATA:message}')
insert into grokdata (key,value) values('USERNAME','[a-zA-Z0-9._-]+')
insert into grokdata (key,value) values('USER','%{USERNAME:UNWANTED}')
insert into grokdata (key,value) values('INT','(?:[+-]?(?:[0-9]+))')
insert into grokdata (key,value) values('BASE10NUM','(?<![0-9.+-])(?>[+-]?(?:(?:[0-9]+(?:\.[0-9]+)?)|(?:\.[0-9]+)))')
insert into grokdata (key,value) values('NUMBER','(?:%{BASE10NUM:UNWANTED})')
insert into grokdata (key,value) values('BASE16NUM','(?<![0-9A-Fa-f])(?:[+-]?(?:0x)?(?:[0-9A-Fa-f]+))')
insert into grokdata (key,value) values('BASE16FLOAT','\b(?<![0-9A-Fa-f.])(?:[+-]?(?:0x)?(?:(?:[0-9A-Fa-f]+(?:\.[0-9A-Fa-f]*)?)|(?:\.[0-9A-Fa-f]+)))\b')
insert into grokdata (key,value) values('POSINT','\b(?:[1-9][0-9]*)\b')
insert into grokdata (key,value) values('NONNEGINT','\b(?:[0-9]+)\b')
insert into grokdata (key,value) values('WORD','\b\w+\b')
insert into grokdata (key,value) values('NOTSPACE','\S+')
insert into grokdata (key,value) values('SPACE','\s*')
insert into grokdata (key,value) values('DATA','.*?')
insert into grokdata (key,value) values('GREEDYDATA','.*')
insert into grokdata (key,value) values('UUID','[A-Fa-f0-9]{8}-(?:[A-Fa-f0-9]{4}-){3}[A-Fa-f0-9]{12}')
insert into grokdata (key,value) values('MAC','(?:%{CISCOMAC:UNWANTED}|%{WINDOWSMAC:UNWANTED}|%{COMMONMAC:UNWANTED})')
insert into grokdata (key,value) values('CISCOMAC','(?:(?:[A-Fa-f0-9]{4}\.){2}[A-Fa-f0-9]{4})')
insert into grokdata (key,value) values('WINDOWSMAC','(?:(?:[A-Fa-f0-9]{2}-){5}[A-Fa-f0-9]{2})')
insert into grokdata (key,value) values('COMMONMAC','(?:(?:[A-Fa-f0-9]{2}:){5}[A-Fa-f0-9]{2})')
insert into grokdata (key,value) values('IPV6','((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?')
insert into grokdata (key,value) values('IPV4','(?<![0-9])(?:(?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2})[.](?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2})[.](?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2})[.](?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2}))(?![0-9])')
insert into grokdata (key,value) values('IP','(?:%{IPV6:UNWANTED}|%{IPV4:UNWANTED})')
insert into grokdata (key,value) values('HOSTNAME','\b(?:[0-9A-Za-z][0-9A-Za-z-]{0,62})(?:\.(?:[0-9A-Za-z][0-9A-Za-z-]{0,62}))*(\.?|\b)')
insert into grokdata (key,value) values('HOST','%{HOSTNAME:UNWANTED}')
insert into grokdata (key,value) values('IPORHOST','(?:%{HOSTNAME:UNWANTED}|%{IP:UNWANTED})')
insert into grokdata (key,value) values('HOSTPORT','(?:%{IPORHOST}:%{POSINT:PORT})')
insert into grokdata (key,value) values('PATH','(?:%{UNIXPATH}|%{WINPATH})')
insert into grokdata (key,value) values('UNIXPATH','(?>/(?>[\w_%!$@:.,~-]+|\\.)*)+')
insert into grokdata (key,value) values('TTY','(?:/dev/(pts|tty([pq])?)(\w+)?/?(?:[0-9]+))')
insert into grokdata (key,value) values('WINPATH','(?>[A-Za-z]+:|\\)(?:\\[^\\?*]*)+')
insert into grokdata (key,value) values('URIPROTO','[A-Za-z]+(\+[A-Za-z+]+)?')
insert into grokdata (key,value) values('URIHOST','%{IPORHOST}(?::%{POSINT:port})?')
insert into grokdata (key,value) values('URIPATH','(?:/[A-Za-z0-9$.+!*''(){},~:;=@#%_\-]*)+')
insert into grokdata (key,value) values('URIPARAM','\?[A-Za-z0-9$.+!*''|(){},~@#%&/=:;_?\-\[\]]*')
insert into grokdata (key,value) values('URIPATHPARAM','%{URIPATH}(?:%{URIPARAM})?')
insert into grokdata (key,value) values('URI','%{URIPROTO}://(?:%{USER}(?::[^@]*)?@)?(?:%{URIHOST})?(?:%{URIPATHPARAM})?')
insert into grokdata (key,value) values('MONTH','\b(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\b')
insert into grokdata (key,value) values('MONTHNUM','(?:0?[1-9]|1[0-2])')
insert into grokdata (key,value) values('MONTHNUM2','(?:0[1-9]|1[0-2])')
insert into grokdata (key,value) values('MONTHDAY','(?:(?:0[1-9])|(?:[12][0-9])|(?:3[01])|[1-9])')
insert into grokdata (key,value) values('DAY','(?:Mon(?:day)?|Tue(?:sday)?|Wed(?:nesday)?|Thu(?:rsday)?|Fri(?:day)?|Sat(?:urday)?|Sun(?:day)?)')
insert into grokdata (key,value) values('YEAR','(?>\d\d){1,2}')
insert into grokdata (key,value) values('HOUR','(?:2[0123]|[01]?[0-9])')
insert into grokdata (key,value) values('MINUTE','(?:[0-5][0-9])')
insert into grokdata (key,value) values('SECOND','(?:(?:[0-5]?[0-9]|60)(?:[:.,][0-9]+)?)')
insert into grokdata (key,value) values('TIME','(?!<[0-9])%{HOUR}:%{MINUTE}(?::%{SECOND})(?![0-9])')
insert into grokdata (key,value) values('DATE_US','%{MONTHNUM}[/-]%{MONTHDAY}[/-]%{YEAR}')
insert into grokdata (key,value) values('DATE_EU','%{MONTHDAY}[./-]%{MONTHNUM}[./-]%{YEAR}')
insert into grokdata (key,value) values('ISO8601_TIMEZONE','(?:Z|[+-]%{HOUR}(?::?%{MINUTE}))')
insert into grokdata (key,value) values('ISO8601_SECOND','(?:%{SECOND}|60)')
insert into grokdata (key,value) values('TIMESTAMP_ISO8601','%{YEAR}-%{MONTHNUM}-%{MONTHDAY}[T ]%{HOUR}:?%{MINUTE}(?::?%{SECOND})?%{ISO8601_TIMEZONE}?')
insert into grokdata (key,value) values('DATE','%{DATE_US}|%{DATE_EU}')
insert into grokdata (key,value) values('DATESTAMP','%{DATE}[- ]%{TIME}')
insert into grokdata (key,value) values('TZ','(?:[PMCE][SD]T|UTC)')
insert into grokdata (key,value) values('DATESTAMP_RFC822','%{DAY} %{MONTH} %{MONTHDAY} %{YEAR} %{TIME} %{TZ}')
insert into grokdata (key,value) values('DATESTAMP_RFC2822','%{DAY}, %{MONTHDAY} %{MONTH} %{YEAR} %{TIME} %{ISO8601_TIMEZONE}')
insert into grokdata (key,value) values('DATESTAMP_OTHER','%{DAY} %{MONTH} %{MONTHDAY} %{TIME} %{TZ} %{YEAR}')
insert into grokdata (key,value) values('DATESTAMP_EVENTLOG','%{YEAR}%{MONTHNUM2}%{MONTHDAY}%{HOUR}%{MINUTE}%{SECOND}')
insert into grokdata (key,value) values('SYSLOGTIMESTAMP','%{MONTH} +%{MONTHDAY} %{TIME}')
insert into grokdata (key,value) values('PROG','(?:[\w._/%-]+)')
insert into grokdata (key,value) values('SYSLOGPROG','%{PROG:program}(?:\[%{POSINT:pid}\])?')
insert into grokdata (key,value) values('SYSLOGHOST','%{IPORHOST}')
insert into grokdata (key,value) values('SYSLOGFACILITY','<%{NONNEGINT:facility}.%{NONNEGINT:priority}>')
insert into grokdata (key,value) values('HTTPDATE','%{MONTHDAY}/%{MONTH}/%{YEAR}:%{TIME} %{INT}')
insert into grokdata (key,value) values('QS','%{QUOTEDSTRING:UNWANTED}')
insert into grokdata (key,value) values('SYSLOGBASE','%{SYSLOGTIMESTAMP:timestamp} (?:%{SYSLOGFACILITY} )?%{SYSLOGHOST:logsource} %{SYSLOGPROG}:')
insert into grokdata (key,value) values('MESSAGESLOG','%{SYSLOGBASE} %{DATA}')
insert into grokdata (key,value) values('COMMONAPACHELOG','%{IPORHOST:clientip} %{USER:ident} %{USER:auth} \[%{HTTPDATE:timestamp}\] "(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})" %{NUMBER:response} (?:%{NUMBER:bytes}|-)')
insert into grokdata (key,value) values('COMBINEDAPACHELOG','%{COMMONAPACHELOG} %{QS:referrer} %{QS:agent}')
insert into grokdata (key,value) values('COMMONAPACHELOG_DATATYPED','%{IPORHOST:clientip} %{USER:ident;boolean} %{USER:auth} \[%{HTTPDATE:timestamp;date;dd/MMM/yyyy:HH:mm:ss Z}\] "(?:%{WORD:verb;string} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion;float})?|%{DATA:rawrequest})" %{NUMBER:response;int} (?:%{NUMBER:bytes;long}|-)')
insert into grokdata (key,value) values('LOGLEVEL','([A|a]lert|ALERT|[T|t]race|TRACE|[D|d]ebug|DEBUG|[N|n]otice|NOTICE|[I|i]nfo|INFO|[W|w]arn?(?:ing)?|WARN?(?:ING)?|[E|e]rr?(?:or)?|ERR?(?:OR)?|[C|c]rit?(?:ical)?|CRIT?(?:ICAL)?|[F|f]atal|FATAL|[S|s]evere|SEVERE|EMERG(?:ENCY)?|[Ee]merg(?:ency)?)')